### ISSUE TITLE
遇到一个GitHub Action中`if`判断的疑问

### ISSUE THREAD

**Issue by maboloshi** [maboloshi/github-chinese#75]
https://github.com/maboloshi/github-chinese/blob/a7ecd13383165eda79041656b795945538cbecee/.github/workflows/main.user.js_version_update.yaml#L38

与
```yml
        if: |
          ${{ env.AHEAD == 'true' }} &&
          ${{ env.CHANGES_DETECTED == 'true' }}
```
貌似不等效
当环境变量`CHANGES_DETECTED`不存在时 后续代码依然执行

经实测
https://github.com/maboloshi/inuyasha/actions/runs/7032676499/job/19136906521
```yml
name: step中if测试
on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: 设置环境变量
        env:
          AHEAD : 'true'
        run: echo "此处设置环境变量 AHEAD"

      - name: 测试环境变量 CHANGES_DETECTED 不存在的情况-1
        if: |
          ${{ env.AHEAD == 'true' }} &&
          ${{ env.CHANGES_DETECTED == 'true' }}
        run: |
          echo "理论上不应该看到这个输出"

      - name: 测试环境变量 CHANGES_DETECTED 不存在的情况-2
        if: ${{ env.AHEAD == 'true' && env.CHANGES_DETECTED == 'true' }}
        run: |
          echo "理论上此步骤跳过"

      - name: 测试环境变量 CHANGES_DETECTED 不存在的情况-3
        env:
          CHANGES_DETECTED : 'false'
        if: |
          ${{ env.AHEAD == 'true' }} &&
          ${{ env.CHANGES_DETECTED == 'true' }}
        run: |
          echo "理论上不应该看到这个输出"

      - name: 测试环境变量 CHANGES_DETECTED 不存在的情况-4
        if: |
            ${{ env.AHEAD == 'true' }} &&
            ${{ env.CHANGES_DETECTED == 'true' }}
        run: |
          echo "理论上不应该看到这个输出"

      - name: 后续操作
        run: |
          echo "后续操作"

```
这种写法
```
        if: |
            ${{ env.AHEAD == 'true' }} &&
            ${{ env.CHANGES_DETECTED == 'true' }}
```
第二句不管是否为真 只要第一句为真 整体为真 与预想的不一致

这种行为可能是由于GitHub Action 对于多行 if 表达式在解析时被视为一系列的单行表达式，而不是一个整体。因此，即使后面的条件为 false，只要第一行条件为 true，整个表达式被认为是 true。

以下貌似能正确执行
https://github.com/maboloshi/github-chinese/blob/a7ecd13383165eda79041656b795945538cbecee/.github/workflows/main.user.js_version_update.yaml#L30-L32
